package lv.bootcamp.shelter.repository;

import lv.bootcamp.shelter.model.Adopter;

import java.util.Optional;

// Generated by GitHub Copilot
public interface AdopterRepository {
    Optional<Adopter> findById(Long id);
}
